import pandas as pd

cols = ['symbol',
        'adp_100',
        'adp_200',
        'adp_50',
        'adv_21',
        'adv_30',
        'adv_90',
        'beta_x',
        'beta_y',
        'chg',
        'cl',
        'div',
        'dollar_value',
        'eps',
        'hi',
        'iad',
        'incr_vl',
        'last',
        'lo',
        'opn',
        'pchg',
        'pcls',
        'pe',
        'phi',
        'plo',
        'popn',
        'pr_adp_100',
        'pr_adp_200',
        'pr_adp_50',
        'pr_date',
        'prbook',
        'prchg',
        'pvol',
        'sho',
        'tcond',
        'timestamp',
        'tr_num',
        'vl',
        'volatility12',
        'vwap',
        'wk52hi',
        'wk52hidate',
        'wk52lo',
        'wk52lodate',
        'yield',
        'marketcap',
        'week52high',
        'week52low',
        'week52highSplitAdjustOnly',
        'week52lowSplitAdjustOnly',
        'week52change',
        'sharesOutstanding',
        'avg10Volume',
        'avg30Volume',
        'day200MovingAvg',
        'day50MovingAvg',
        'employees',
        'ttmEPS',
        'ttmDividendRate',
        'dividendYield',
        'peRatio',
        'maxChangePercent',
        'year5ChangePercent',
        'year2ChangePercent',
        'year1ChangePercent',
        'ytdChangePercent',
        'month6ChangePercent',
        'month3ChangePercent',
        'month1ChangePercent',
        'day30ChangePercent',
        'day5ChangePercent',
        'nope_metric',
        'nope_adv_21',
        'net_idelta',
        'net_igamma',
        'noge',
        'noge_21',
        'mw_idelta',
        'mw_igamma',
        'mw_itheta',
        'mw_ivega',
        'sp',
        'etf',
        'qqq',
        'df_date']

df = pd.DataFrame([])
df['cols'] = cols
df.to_csv('col_df.csv', compression='gzip', index=False)

col_df = pd.read_csv('col_df.csv', compression='gzip')
cols = list(col_df['cols'])
print (cols)
